#!/bin/bash

mount -t tmpfs shmfs -o size=4g /dev/shm

date
su -s /bin/bash oracle -c "cd /app/setup/database/ && ./runInstaller -ignoreSysPrereqs -ignorePrereq -silent -noconfig -responseFile /app/setup/db_install.rsp"
